from __future__ import annotations

from pathlib import Path

import pytest

from spec_harvester.go_public_api import (
    GO_PUBLIC_API_ANALYZER_ID,
    analyze_go_public_api,
    go_source_files,
)


def test_analyze_go_public_api_extracts_exported_declarations(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    repo.mkdir()
    (repo / "go.mod").write_text("module example.com/demo\n\ngo 1.24\n", encoding="utf-8")
    (repo / "api.go").write_text(
        """
package demo

const (
    Version, BuildNumber = "1.0.0", 7
    privateConst = "hidden"
)

const Build = "dev"

var DefaultWriter, DefaultReader Writer

var (
    DefaultMode = "debug"
    hiddenMode = "release"
)

type Engine struct {
    hidden string
}

type HandlerFunc func(*Context)

type (
    RouterGroup struct {}
    Binder interface { Bind(any) error }
)

type Set[T any] struct {}

type router struct {}

func New() *Engine { return &Engine{} }
func Map[T any](items []T, fn func(T) T) []T { return items }
func hidden() {}
func (engine *Engine) Run(addr ...string) error { return nil }
func (set *Set[T]) Add(item T) {}
func (router *router) HiddenReceiver() {}
""",
        encoding="utf-8",
    )
    subpackage = repo / "binding"
    subpackage.mkdir()
    (subpackage / "binding.go").write_text(
        """
package binding

type Binding interface {
    Name() string
}

func Default(method string, contentType string) Binding { return nil }
""",
        encoding="utf-8",
    )

    index = analyze_go_public_api(repo, source_revision="abc123")

    assert index["sourceRevision"] == "abc123"
    assert index["analyzers"] == [
        {
            "id": GO_PUBLIC_API_ANALYZER_ID,
            "version": "0.1.0",
            "execution": "none",
            "networkAccess": "none",
            "packageScripts": "not_run",
            "confidence": "medium",
        }
    ]
    assert index["summary"] == {
        "status": "complete",
        "packageCount": 2,
        "entrypointCount": 2,
        "symbolCount": 17,
        "diagnosticCount": 0,
    }
    packages = {package["path"]: package for package in index["packages"]}
    assert packages["."]["id"] == "example.com/demo"
    assert packages["binding"]["id"] == "example.com/demo/binding"

    root_symbols = {symbol["name"]: symbol for symbol in packages["."]["entrypoints"][0]["symbols"]}
    assert sorted(root_symbols) == [
        "Binder",
        "Build",
        "BuildNumber",
        "DefaultMode",
        "DefaultReader",
        "DefaultWriter",
        "Engine",
        "Engine.Run",
        "HandlerFunc",
        "Map",
        "New",
        "RouterGroup",
        "Set",
        "Set.Add",
        "Version",
    ]
    assert root_symbols["Binder"]["kind"] == "interface"
    assert root_symbols["Engine"]["kind"] == "struct"
    assert root_symbols["HandlerFunc"]["kind"] == "type"
    assert root_symbols["RouterGroup"]["kind"] == "struct"
    assert root_symbols["Set"]["kind"] == "struct"
    assert root_symbols["Map"]["signature"] == "func Map[T any](items []T, fn func(T) T) []T"
    assert (
        root_symbols["Engine.Run"]["signature"] == "func (engine *Engine) Run(addr ...string) error"
    )
    assert root_symbols["Set.Add"]["signature"] == "func (set *Set[T]) Add(item T)"
    assert "hidden" not in root_symbols
    assert "router.HiddenReceiver" not in root_symbols

    binding_symbols = {
        symbol["name"]: symbol for symbol in packages["binding"]["entrypoints"][0]["symbols"]
    }
    assert sorted(binding_symbols) == ["Binding", "Default"]
    assert binding_symbols["Binding"]["kind"] == "interface"


def test_go_public_api_skips_tests_generated_vendor_and_testdata(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    repo.mkdir()
    (repo / "go.mod").write_text("module example.com/demo\n", encoding="utf-8")
    (repo / "api.go").write_text("package demo\n\nfunc Visible() {}\n", encoding="utf-8")
    (repo / "api_test.go").write_text("package demo\n\nfunc TestVisible() {}\n", encoding="utf-8")
    (repo / "generated.go").write_text(
        "// Code generated by fixture. DO NOT EDIT.\npackage demo\n\nfunc Generated() {}\n",
        encoding="utf-8",
    )
    vendor = repo / "vendor" / "example.com" / "dependency"
    vendor.mkdir(parents=True)
    (vendor / "dep.go").write_text("package dependency\n\nfunc External() {}\n", encoding="utf-8")
    internal = repo / "internal" / "secret"
    internal.mkdir(parents=True)
    (internal / "secret.go").write_text("package secret\n\nfunc Internal() {}\n", encoding="utf-8")
    testdata = repo / "testdata"
    testdata.mkdir()
    (testdata / "fixture.go").write_text("package fixture\n\nfunc Fixture() {}\n", encoding="utf-8")

    index = analyze_go_public_api(repo)

    assert [path.relative_to(repo).as_posix() for path in go_source_files(repo)] == [
        "api.go",
    ]
    package = index["packages"][0]
    assert package["entrypoints"] == [
        {
            "path": "api.go",
            "symbols": [
                {
                    "name": "Visible",
                    "kind": "function",
                    "visibility": "public",
                    "signature": "func Visible()",
                    "evidence": package["entrypoints"][0]["symbols"][0]["evidence"],
                }
            ],
        }
    ]


def test_go_public_api_uses_cache_for_repeated_file_analysis(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    cache = tmp_path / "cache"
    repo.mkdir()
    (repo / "go.mod").write_text("module example.com/demo\n", encoding="utf-8")
    (repo / "api.go").write_text("package demo\n\nfunc Visible() {}\n", encoding="utf-8")

    first = analyze_go_public_api(repo, cache_dir=cache)
    second = analyze_go_public_api(repo, cache_dir=cache)

    assert second == first
    assert second["summary"]["symbolCount"] == 1


def test_go_public_api_reports_no_source_and_bad_source_root(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    repo.mkdir()

    index = analyze_go_public_api(repo, package_id="fallback.go")

    assert index["summary"]["status"] == "failed"
    assert index["packages"] == []
    assert index["diagnostics"] == [
        {
            "level": "warning",
            "message": "No non-generated Go source files were found.",
        }
    ]
    with pytest.raises(ValueError, match="Go source root does not exist"):
        analyze_go_public_api(tmp_path / "missing")


def test_go_public_api_reports_missing_package_declaration(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    repo.mkdir()
    (repo / "go.mod").write_text("module example.com/demo\n", encoding="utf-8")
    (repo / "broken.go").write_text("func MissingPackage() {}\n", encoding="utf-8")

    index = analyze_go_public_api(repo, cache_dir=tmp_path / "cache")
    cached = analyze_go_public_api(repo, cache_dir=tmp_path / "cache")

    assert index["summary"]["status"] == "failed"
    assert cached == index
    assert index["packages"] == []
    assert index["diagnostics"][0]["level"] == "error"
    assert index["diagnostics"][0]["path"] == "broken.go"
    assert "package declaration" in index["diagnostics"][0]["message"]


def test_go_public_api_preserves_comment_markers_inside_strings(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    repo.mkdir()
    (repo / "go.mod").write_text("module example.com/demo\n", encoding="utf-8")
    (repo / "api.go").write_text(
        'package demo\n\nconst URL = "https://example.com/path"\nfunc Visible() {}\n',
        encoding="utf-8",
    )

    index = analyze_go_public_api(repo)

    symbols = index["packages"][0]["entrypoints"][0]["symbols"]
    assert [symbol["name"] for symbol in symbols] == ["URL", "Visible"]


def test_go_source_files_does_not_traverse_symlinked_directories(tmp_path: Path) -> None:
    repo = tmp_path / "go-demo"
    outside = tmp_path / "outside"
    repo.mkdir()
    outside.mkdir()
    (repo / "api.go").write_text("package demo\n\nfunc Visible() {}\n", encoding="utf-8")
    (outside / "outside.go").write_text("package outside\n\nfunc External() {}\n", encoding="utf-8")
    (repo / "linked").symlink_to(outside, target_is_directory=True)

    assert [path.relative_to(repo).as_posix() for path in go_source_files(repo)] == ["api.go"]
