from spec_harvester.semantic_keyword_taxonomy import SEMANTIC_KEYWORD_TAXONOMY


def test_markdown_semantic_hint_terms_preserve_collector_order() -> None:
    assert SEMANTIC_KEYWORD_TAXONOMY.markdown_hint_terms() == (
        "api contract",
        "json schema",
        "api",
        "contract",
        "schema",
        "openapi",
        "endpoint",
        "request",
        "response",
        "webhook",
        "graphql",
        "validation",
        "validator",
        "metadata",
        "manifest",
        "configuration",
        "config",
        "workflow",
        "automation",
        "pipeline",
        "task",
        "cli",
        "command",
        "commands",
        "developer tool",
        "tooling",
        "plugin",
        "extension",
        "sdk",
        "documentation",
        "guide",
        "reference",
        "tutorial",
        "manual",
        "web framework",
        "http framework",
        "microframework",
        "wsgi",
        "asgi",
        "http server",
        "route",
        "routes",
        "routing",
        "router",
        "middleware",
        "middlewares",
        "handler",
        "handlers",
        "request context",
        "application context",
        "blueprint",
        "template",
        "templates",
        "json",
        "session",
        "cookie",
        "cookies",
    )


def test_semantic_domain_rules_keep_stable_ids() -> None:
    rule_ids = {rule.cluster_id for rule in SEMANTIC_KEYWORD_TAXONOMY.domain_rules()}

    assert {
        "api.contract_surface",
        "metadata.schema_validation",
        "workflow.automation_pipeline",
        "developer.tooling_surface",
        "documentation.knowledge_base",
        "web.framework_surface",
        "web.http_routing",
        "web.middleware_pipeline",
        "web.request_response_context",
        "swift.specification_pattern",
        "swift.predicate_composition",
        "swift.context_driven_decisioning",
        "swift.feature_gating",
        "swift.reactive_specification_evaluation",
        "swift.specification_tracing",
    } == rule_ids
