from __future__ import annotations

import hashlib
import json
import re
from importlib.resources import files
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator, FormatChecker

from spec_harvester.ai_semantic_author_schema import load_ai_semantic_author_schema
from spec_harvester.experimental_intent_policy import (
    EXPERIMENTAL_INTENT_ID_PATTERN,
    GENERIC_OBSERVED_INTENT_IDS,
    candidate_namespace_tokens,
    experimental_intent_suffix,
    load_experimental_intent_decision_policy,
)

QUALITY_REPORT_API_VERSION = "spec-harvester.semantic-proposal-quality/v0"
QUALITY_REPORT_KIND = "SpecHarvesterSemanticProposalQualityReport"
POLICY_FILENAME = "semantic-author-quality-thresholds-v0.json"
POLICY_SOURCE_PATH = (
    "tests/fixtures/semantic_author_quality_policy/p55-t5-semantic-quality-thresholds.example.json"
)

PROVIDER_AUTHORITY_PATTERNS = (
    re.compile(r"\baccording to (?:the )?(?:model|provider)\b", re.IGNORECASE),
    re.compile(r"\b(?:the )?(?:model|provider) (?:accepts|approves|authorizes)\b", re.IGNORECASE),
    re.compile(r"\bgenerated by (?:codex 5\.3 spark|lm studio)\b", re.IGNORECASE),
)
NUMBER_PATTERN = re.compile(r"(?<![A-Za-z0-9_.])\d+(?:\.\d+)?%?(?![A-Za-z0-9_.])")
WORD_PATTERN = re.compile(r"[a-z0-9]+")
OVERLAP_THRESHOLD = 0.8


def load_semantic_author_quality_policy() -> dict[str, Any]:
    """Load and verify the frozen P55 semantic calibration threshold policy."""
    try:
        raw = (
            files("spec_harvester")
            .joinpath("policies", POLICY_FILENAME)
            .read_text(encoding="utf-8")
        )
    except FileNotFoundError:
        source = Path(__file__).resolve().parents[2] / POLICY_SOURCE_PATH
        try:
            raw = source.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValueError(f"cannot read semantic quality policy: {exc}") from exc
    try:
        policy = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"cannot read semantic quality policy: {exc}") from exc
    validate_semantic_author_quality_policy(policy)
    return policy


def validate_semantic_author_quality_policy(policy: dict[str, Any]) -> None:
    if not isinstance(policy, dict):
        raise ValueError("semantic quality policy must be an object")
    expected = {
        "purposeAccuracyRate": ("greater_than_or_equal", 0.85),
        "evidenceSupportedClaimRate": ("greater_than_or_equal", 0.95),
        "schemaValidProposalRate": ("equal", 1.0),
        "reviewerEditBurdenRate": ("less_than_or_equal", 0.25),
    }
    if (
        policy.get("apiVersion") != "spec-harvester.semantic-author-quality-policy/v0"
        or policy.get("kind") != "SpecHarvesterSemanticAuthorQualityPolicy"
        or policy.get("schemaVersion") != 1
        or policy.get("authority") != "maintainer_frozen_calibration_thresholds"
        or policy.get("frozenByTask") != "P55-T5"
        or policy.get("requiredBeforeTask") != "P55-T9"
    ):
        raise ValueError("semantic quality policy identity is invalid")
    metrics = policy.get("metrics")
    if not isinstance(metrics, dict) or set(metrics) != set(expected):
        raise ValueError("semantic quality policy metrics are invalid")
    for name, (operator, threshold) in expected.items():
        if metrics.get(name) != {"operator": operator, "threshold": threshold}:
            raise ValueError(f"semantic quality policy metric is not frozen: {name}")
    if policy.get("changeControl") != {
        "calibrationMayRedefineThresholds": False,
        "separateReviewedPolicyRevisionRequired": True,
    }:
        raise ValueError("semantic quality policy change control is invalid")
    digest = policy.get("policySha256")
    if not isinstance(digest, str) or digest != _digest_without(policy, "policySha256"):
        raise ValueError("semantic quality policy digest is stale")


def evaluate_semantic_proposal_quality(
    input_pack: dict[str, Any],
    semantic_pass: dict[str, Any],
    *,
    policy: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Evaluate one P55 proposal without invoking a provider or changing authority."""
    policy = policy or load_semantic_author_quality_policy()
    validate_semantic_author_quality_policy(policy)
    decision_policy = load_experimental_intent_decision_policy()
    diagnostics: list[dict[str, Any]] = []
    proposal = semantic_pass.get("proposal")
    request = input_pack.get("request")
    if not isinstance(proposal, dict) or not isinstance(request, dict):
        diagnostics.append(_diagnostic("proposal_record_missing", "error"))
        return _report(input_pack, semantic_pass, policy, diagnostics, _empty_metrics(False))

    schema_valid = _validate_schema(proposal, diagnostics)
    _validate_envelope_bindings(input_pack, semantic_pass, proposal, decision_policy, diagnostics)
    evidence_by_binding = _validate_evidence(input_pack, proposal, diagnostics)
    _validate_candidate_yaml(input_pack, diagnostics)
    if schema_valid:
        _validate_claims(proposal, evidence_by_binding, diagnostics)
        _validate_intents(input_pack, proposal, decision_policy, diagnostics)

    metrics = _metrics(proposal, diagnostics, schema_valid)
    return _report(input_pack, semantic_pass, policy, diagnostics, metrics)


def _validate_schema(proposal: dict[str, Any], diagnostics: list[dict[str, Any]]) -> bool:
    schema = {
        "$ref": "#/$defs/proposal",
        "$defs": load_ai_semantic_author_schema()["$defs"],
    }
    errors = sorted(
        Draft202012Validator(schema, format_checker=FormatChecker()).iter_errors(proposal),
        key=lambda error: list(error.absolute_path),
    )
    if errors:
        diagnostics.append(
            _diagnostic(
                "proposal_schema_invalid",
                "error",
                detail=errors[0].message[:500],
            )
        )
        return False
    expected_digest = _digest_without(proposal, "proposalSha256")
    if proposal["proposalSha256"] != expected_digest:
        diagnostics.append(_diagnostic("proposal_digest_stale", "error"))
    return True


def _validate_envelope_bindings(
    pack: dict[str, Any],
    semantic_pass: dict[str, Any],
    proposal: dict[str, Any],
    decision_policy: dict[str, Any],
    diagnostics: list[dict[str, Any]],
) -> None:
    candidate_id = pack.get("candidateId")
    source_digest = pack.get("sourceBundleSha256")
    request = pack.get("request", {})
    if semantic_pass.get("kind") != "SpecHarvesterSemanticAuthorPass":
        diagnostics.append(_diagnostic("semantic_pass_kind_invalid", "error"))
    if (
        request.get("candidateId") != candidate_id
        or request.get("sourceBundleSha256") != source_digest
    ):
        diagnostics.append(_diagnostic("request_binding_mismatch", "error"))
    if (
        proposal.get("candidateId") != candidate_id
        or semantic_pass.get("candidateId") != candidate_id
    ):
        diagnostics.append(_diagnostic("candidate_binding_mismatch", "error"))
    if (
        proposal.get("sourceBundleSha256") != source_digest
        or semantic_pass.get("sourceBundleSha256") != source_digest
    ):
        diagnostics.append(_diagnostic("source_bundle_binding_mismatch", "error"))
    policy_binding = semantic_pass.get("experimentalIntentDecisionPolicy")
    if (
        not isinstance(policy_binding, dict)
        or policy_binding.get("apiVersion") != decision_policy["apiVersion"]
        or policy_binding.get("kind") != decision_policy["kind"]
        or policy_binding.get("policySha256") != decision_policy["policySha256"]
        or policy_binding.get("frozenByTask") != "P55-T10A"
        or policy_binding.get("authority") != "maintainer_bounded_proposal_policy"
    ):
        diagnostics.append(_diagnostic("experimental_intent_policy_binding_invalid", "error"))


def _validate_evidence(
    pack: dict[str, Any],
    proposal: dict[str, Any],
    diagnostics: list[dict[str, Any]],
) -> dict[tuple[str, str, str, str, str], dict[str, Any]]:
    content_by_binding: dict[tuple[str, str, str, str, str], dict[str, Any]] = {}
    source_digest = pack.get("sourceBundleSha256")
    evidence = pack.get("evidence", [])
    if not isinstance(evidence, list) or _source_bundle_digest(evidence) != source_digest:
        diagnostics.append(_diagnostic("source_bundle_digest_stale", "error"))
        evidence = evidence if isinstance(evidence, list) else []
    for item in evidence:
        if not isinstance(item, dict):
            continue
        binding = _binding_tuple(item)
        if binding is None:
            continue
        content = item.get("content")
        if (
            not isinstance(content, str)
            or hashlib.sha256(content.encode()).hexdigest() != item.get("sha256")
            or len(content.encode()) != item.get("byteCount")
            or item.get("sourceBundleSha256") != source_digest
        ):
            diagnostics.append(
                _diagnostic(
                    "evidence_content_binding_stale",
                    "error",
                    subject=str(item.get("sourcePath", "unknown")),
                )
            )
            continue
        content_by_binding[binding] = item
    allowed = {
        binding
        for item in pack.get("request", {}).get("evidence", [])
        if (binding := _binding_tuple(item)) is not None
    }
    for claim in proposal.get("claims", []):
        if not isinstance(claim, dict):
            continue
        for item in claim.get("evidence", []):
            binding = _binding_tuple(item) if isinstance(item, dict) else None
            if binding not in allowed or binding not in content_by_binding:
                diagnostics.append(
                    _diagnostic(
                        "claim_evidence_not_allowlisted",
                        "error",
                        subject=str(claim.get("id", "unknown")),
                    )
                )
    return content_by_binding


def _validate_candidate_yaml(pack: dict[str, Any], diagnostics: list[dict[str, Any]]) -> None:
    documents: dict[str, dict[str, Any]] = {}
    for item in pack.get("evidence", []):
        if not isinstance(item, dict) or item.get("class") != "validated_candidate_yaml":
            continue
        try:
            document = yaml.safe_load(item.get("content"))
        except yaml.YAMLError:
            document = None
        if not isinstance(document, dict):
            diagnostics.append(
                _diagnostic("candidate_yaml_invalid", "error", subject=str(item.get("sourcePath")))
            )
            continue
        documents[str(item.get("sourcePath"))] = document
    manifests = [value for path, value in documents.items() if path.endswith("specpm.yaml")]
    boundaries = {path: value for path, value in documents.items() if path.endswith(".spec.yaml")}
    if len(manifests) != 1:
        diagnostics.append(_diagnostic("candidate_manifest_missing_or_duplicate", "error"))
        return
    manifest = manifests[0]
    candidate_id = pack.get("candidateId")
    if manifest.get("metadata", {}).get("id") != candidate_id:
        diagnostics.append(_diagnostic("manifest_candidate_id_mismatch", "error"))
    manifest_capabilities = set(
        _string_list(manifest.get("index", {}).get("provides", {}).get("capabilities"))
    )
    boundary_capabilities: set[str] = set()
    boundary_intents: set[str] = set()
    for boundary in boundaries.values():
        if boundary.get("kind") != "BoundarySpec":
            diagnostics.append(_diagnostic("boundary_kind_invalid", "error"))
            continue
        for capability in boundary.get("provides", {}).get("capabilities", []):
            if isinstance(capability, dict) and isinstance(capability.get("id"), str):
                boundary_capabilities.add(capability["id"])
                boundary_intents.update(_string_list(capability.get("intentIds")))
    expected_prefix = f"{candidate_id}."
    for capability_id in sorted(manifest_capabilities | boundary_capabilities):
        if not capability_id.startswith(expected_prefix):
            diagnostics.append(
                _diagnostic(
                    "capability_namespace_violation",
                    "error",
                    subject=capability_id,
                )
            )
    if manifest_capabilities != boundary_capabilities:
        diagnostics.append(_diagnostic("manifest_boundary_capability_mismatch", "error"))
    manifest_intents = set(
        _string_list(manifest.get("index", {}).get("provides", {}).get("intents"))
    )
    if manifest_intents != boundary_intents:
        diagnostics.append(_diagnostic("manifest_boundary_intent_mismatch", "error"))
    declared_paths = {
        item.get("path")
        for item in manifest.get("specs", [])
        if isinstance(item, dict) and isinstance(item.get("path"), str)
    }
    if declared_paths != set(boundaries):
        diagnostics.append(_diagnostic("manifest_boundary_path_mismatch", "error"))


def _validate_claims(
    proposal: dict[str, Any],
    evidence_by_binding: dict[tuple[str, str, str, str, str], dict[str, Any]],
    diagnostics: list[dict[str, Any]],
) -> None:
    claims = proposal["claims"]
    for claim in claims:
        text = claim["text"]
        if any(pattern.search(text) for pattern in PROVIDER_AUTHORITY_PATTERNS):
            diagnostics.append(
                _diagnostic("provider_specific_authority_wording", "error", subject=claim["id"])
            )
        cited_content = "\n".join(
            str(evidence_by_binding[binding]["content"])
            for item in claim["evidence"]
            if (binding := _binding_tuple(item)) in evidence_by_binding
        )
        cited_numbers = set(NUMBER_PATTERN.findall(cited_content))
        unsupported_numbers = sorted(set(NUMBER_PATTERN.findall(text)) - cited_numbers)
        if unsupported_numbers:
            diagnostics.append(
                _diagnostic(
                    "unsupported_quantitative_claim",
                    "error",
                    subject=claim["id"],
                    detail=", ".join(unsupported_numbers),
                )
            )
    for index, left in enumerate(claims):
        for right in claims[index + 1 :]:
            if left["kind"] != right["kind"]:
                continue
            if _text_overlap(left["text"], right["text"]) >= OVERLAP_THRESHOLD:
                diagnostics.append(
                    _diagnostic(
                        "overlapping_semantic_claims",
                        "warning",
                        subject=f"{left['id']}:{right['id']}",
                    )
                )


def _validate_intents(
    pack: dict[str, Any],
    proposal: dict[str, Any],
    decision_policy: dict[str, Any],
    diagnostics: list[dict[str, Any]],
) -> None:
    observed = {
        item.get("intentId"): item.get("observedIntentSha256")
        for item in pack.get("observedIntents", [])
        if isinstance(item, dict)
    }
    claim_ids = {claim["id"] for claim in proposal["claims"]}
    claims_by_id = {claim["id"]: claim for claim in proposal["claims"]}
    experiments = [
        decision
        for decision in proposal["intentDecisions"]
        if decision["state"] == "proposed_experimental"
    ]
    if len(experiments) > decision_policy["decisionRules"]["maxExperimentalIntentCount"]:
        diagnostics.append(_diagnostic("experimental_intent_count_exceeded", "error"))
    generic_reuse_ids = {
        decision["intentId"]
        for decision in proposal["intentDecisions"]
        if decision["state"] == "proposed_reuse"
        and decision["intentId"] in GENERIC_OBSERVED_INTENT_IDS
    }
    if experiments and generic_reuse_ids:
        diagnostics.append(
            _diagnostic(
                "experimental_intent_retains_generic_reuse",
                "error",
                detail=", ".join(sorted(generic_reuse_ids)),
            )
        )
    seen: set[str] = set()
    for decision in proposal["intentDecisions"]:
        intent_id = decision["intentId"]
        if intent_id in seen:
            diagnostics.append(
                _diagnostic(
                    (
                        "duplicate_experimental_intent"
                        if decision["state"] == "proposed_experimental"
                        else "duplicate_intent_decision"
                    ),
                    "error" if decision["state"] == "proposed_experimental" else "warning",
                    subject=intent_id,
                )
            )
        seen.add(intent_id)
        if intent_id in GENERIC_OBSERVED_INTENT_IDS:
            diagnostics.append(_diagnostic("generic_intent_reuse", "warning", subject=intent_id))
        if decision["state"] == "proposed_reuse":
            if observed.get(intent_id) != decision["observedIntentSha256"]:
                diagnostics.append(
                    _diagnostic("observed_intent_binding_stale", "error", subject=intent_id)
                )
            if intent_id in GENERIC_OBSERVED_INTENT_IDS:
                rationale = claims_by_id.get(decision["rationaleClaimId"])
                if rationale is None or rationale["kind"] != "nearby_intent_difference":
                    diagnostics.append(
                        _diagnostic(
                            "generic_intent_reuse_comparison_missing",
                            "error",
                            subject=intent_id,
                        )
                    )
        elif not intent_id.startswith("intent.experimental."):
            diagnostics.append(
                _diagnostic("experimental_intent_namespace_invalid", "error", subject=intent_id)
            )
        elif EXPERIMENTAL_INTENT_ID_PATTERN.fullmatch(intent_id) is None or not intent_id.endswith(
            f".{experimental_intent_suffix(str(pack.get('sourceBundleSha256', '')))}"
        ):
            diagnostics.append(
                _diagnostic(
                    "experimental_intent_identifier_not_collision_bound",
                    "error",
                    subject=intent_id,
                )
            )
        elif set(intent_id.split(".")[2].split("_")) & candidate_namespace_tokens(
            str(pack.get("candidateId", ""))
        ):
            diagnostics.append(
                _diagnostic(
                    "experimental_intent_identifier_leaks_candidate_namespace",
                    "error",
                    subject=intent_id,
                )
            )
        if decision["state"] == "proposed_experimental":
            unknown_nearby = sorted(set(decision["nearbyIntentIds"]) - set(observed))
            if unknown_nearby:
                diagnostics.append(
                    _diagnostic(
                        "experimental_intent_nearby_unknown",
                        "error",
                        subject=intent_id,
                        detail=", ".join(unknown_nearby),
                    )
                )
            nearby_claim_ids = decision["nearbyIntentClaimIds"]
            if len(nearby_claim_ids) != len(decision["nearbyIntentIds"]):
                diagnostics.append(
                    _diagnostic(
                        "experimental_intent_nearby_binding_count_mismatch",
                        "error",
                        subject=intent_id,
                    )
                )
            if any(
                claims_by_id.get(claim_id, {}).get("kind") != "nearby_intent_difference"
                for claim_id in nearby_claim_ids
            ):
                diagnostics.append(
                    _diagnostic(
                        "experimental_intent_nearby_difference_claim_invalid",
                        "error",
                        subject=intent_id,
                    )
                )
            user_need = claims_by_id.get(decision["userNeedClaimId"])
            if user_need is None or user_need["kind"] != "purpose":
                diagnostics.append(
                    _diagnostic("experimental_intent_user_need_invalid", "error", subject=intent_id)
                )
            if any(
                claims_by_id.get(claim_id, {}).get("kind") != "non_goal"
                for claim_id in decision["nonGoalClaimIds"]
            ):
                diagnostics.append(
                    _diagnostic("experimental_intent_non_goal_invalid", "error", subject=intent_id)
                )
        referenced_claim_ids = (
            {decision["rationaleClaimId"]}
            if decision["state"] == "proposed_reuse"
            else {
                decision["userNeedClaimId"],
                *decision["nearbyIntentClaimIds"],
                *decision["nonGoalClaimIds"],
            }
        )
        unknown_claim_ids = sorted(referenced_claim_ids - claim_ids)
        if unknown_claim_ids:
            diagnostics.append(
                _diagnostic(
                    "intent_claim_reference_unknown",
                    "error",
                    subject=intent_id,
                    detail=", ".join(unknown_claim_ids),
                )
            )
        for observed_id in observed:
            if (
                decision["state"] == "proposed_experimental"
                and _intent_overlap(intent_id, str(observed_id)) >= OVERLAP_THRESHOLD
            ):
                diagnostics.append(
                    _diagnostic(
                        "experimental_intent_overlaps_observed",
                        "warning",
                        subject=f"{intent_id}:{observed_id}",
                    )
                )
                diagnostics.append(
                    _diagnostic(
                        "experimental_intent_false_novelty_risk",
                        "error",
                        subject=f"{intent_id}:{observed_id}",
                    )
                )


def _metrics(
    proposal: dict[str, Any], diagnostics: list[dict[str, Any]], schema_valid: bool
) -> dict[str, Any]:
    claims = proposal.get("claims", []) if isinstance(proposal.get("claims"), list) else []
    evidence_count = sum(
        len(claim.get("evidence", [])) for claim in claims if isinstance(claim, dict)
    )
    unsupported = sum(item["code"] == "claim_evidence_not_allowlisted" for item in diagnostics)
    return {
        "schemaValid": schema_valid,
        "claimCount": len(claims),
        "purposeClaimCount": sum(
            isinstance(claim, dict) and claim.get("kind") == "purpose" for claim in claims
        ),
        "evidenceBindingCount": evidence_count,
        "supportedEvidenceBindingCount": max(0, evidence_count - unsupported),
        "evidenceSupportRate": (
            round(max(0, evidence_count - unsupported) / evidence_count, 4)
            if evidence_count
            else 0.0
        ),
        "genericIntentCount": sum(item["code"] == "generic_intent_reuse" for item in diagnostics),
        "duplicateIntentCount": sum(
            item["code"] == "duplicate_intent_decision" for item in diagnostics
        ),
        "overlappingClaimPairCount": sum(
            item["code"] == "overlapping_semantic_claims" for item in diagnostics
        ),
    }


def _empty_metrics(schema_valid: bool) -> dict[str, Any]:
    return {
        "schemaValid": schema_valid,
        "claimCount": 0,
        "purposeClaimCount": 0,
        "evidenceBindingCount": 0,
        "supportedEvidenceBindingCount": 0,
        "evidenceSupportRate": 0.0,
        "genericIntentCount": 0,
        "duplicateIntentCount": 0,
        "overlappingClaimPairCount": 0,
    }


def _report(
    pack: dict[str, Any],
    semantic_pass: dict[str, Any],
    policy: dict[str, Any],
    diagnostics: list[dict[str, Any]],
    metrics: dict[str, Any],
) -> dict[str, Any]:
    diagnostics = sorted(
        diagnostics,
        key=lambda item: (
            0 if item["severity"] == "error" else 1,
            item["code"],
            item.get("subject", ""),
        ),
    )
    error_count = sum(item["severity"] == "error" for item in diagnostics)
    warning_count = len(diagnostics) - error_count
    status = (
        "rejected"
        if error_count
        else "review_required"
        if warning_count
        else "eligible_for_calibration"
    )
    proposal = semantic_pass.get("proposal", {})
    return {
        "apiVersion": QUALITY_REPORT_API_VERSION,
        "kind": QUALITY_REPORT_KIND,
        "schemaVersion": 1,
        "authority": "semantic_proposal_quality_evidence_only",
        "candidateId": pack.get("candidateId"),
        "sourceBundleSha256": pack.get("sourceBundleSha256"),
        "proposalSha256": proposal.get("proposalSha256"),
        "policy": {
            "sourcePath": POLICY_SOURCE_PATH,
            "policySha256": policy["policySha256"],
            "frozenByTask": policy["frozenByTask"],
            "requiredBeforeTask": policy["requiredBeforeTask"],
        },
        "status": status,
        "eligibleForCalibration": status != "rejected",
        "summary": {
            "errorCount": error_count,
            "warningCount": warning_count,
            "diagnosticCount": len(diagnostics),
        },
        "metrics": metrics,
        "diagnostics": diagnostics,
        "executionBoundary": {
            "providerInvoked": False,
            "repositoryCodeExecuted": False,
            "packageManagerInvoked": False,
            "materializationPerformed": False,
            "specpmMutated": False,
            "registryMutated": False,
            "publicationPerformed": False,
        },
    }


def _diagnostic(
    code: str,
    severity: str,
    *,
    subject: str | None = None,
    detail: str | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {"code": code, "severity": severity}
    if subject:
        result["subject"] = subject
    if detail:
        result["detail"] = detail
    return result


def _binding_tuple(item: dict[str, Any]) -> tuple[str, str, str, str, str] | None:
    values = tuple(
        item.get(key) for key in ("id", "class", "sourcePath", "sha256", "sourceBundleSha256")
    )
    return values if all(isinstance(value, str) for value in values) else None


def _source_bundle_digest(evidence: list[Any]) -> str | None:
    keys = ("id", "class", "sourcePath", "sha256", "byteCount")
    if any(not isinstance(item, dict) or any(key not in item for key in keys) for item in evidence):
        return None
    bindings = [{key: item[key] for key in keys} for item in evidence]
    return hashlib.sha256(
        json.dumps(bindings, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _string_list(value: Any) -> list[str]:
    return [item for item in value if isinstance(item, str)] if isinstance(value, list) else []


def _text_overlap(left: str, right: str) -> float:
    left_words, right_words = (
        set(WORD_PATTERN.findall(left.lower())),
        set(WORD_PATTERN.findall(right.lower())),
    )
    if min(len(left_words), len(right_words)) < 3:
        return 0.0
    return len(left_words & right_words) / len(left_words | right_words)


def _intent_overlap(left: str, right: str) -> float:
    ignored = {"intent", "experimental"}
    left_words = {
        word
        for word in left.replace("-", ".").replace("_", ".").split(".")
        if word not in ignored and re.fullmatch(r"[0-9a-f]{8}", word) is None
    }
    right_words = {
        word
        for word in right.replace("-", ".").replace("_", ".").split(".")
        if word not in ignored and re.fullmatch(r"[0-9a-f]{8}", word) is None
    }
    return len(left_words & right_words) / len(left_words | right_words) if left_words else 0.0


def _digest_without(value: dict[str, Any], key: str) -> str:
    payload = {name: item for name, item in value.items() if name != key}
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
